apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: queue-training
  annotations:
    volcano.sh/card.quota: '{"NVIDIA-GeForce-RTX-4090":8}'
spec:
  weight: 1
  # 离线任务的队列的优先级需要比在线服务低，
  # 以便在线服务在进行资源抢占的时候优先抢占离线任务的队列资源。
  # 所有离线任务队列使用同一个优先级值即可。
  priority: 20000
  reclaimable: true
  capability:
    cpu: 4
    memory: 4Gi
